// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfkj-u3MJ93ZBUNc_85LXFnFIfniZqKg4',
    appId: '1:337537219073:web:0cf31fccb3d28b368f1e00',
    messagingSenderId: '337537219073',
    projectId: 'furniapp-a28a9',
    authDomain: 'furniapp-a28a9.firebaseapp.com',
    storageBucket: 'furniapp-a28a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzuczFRjTroM1b6s2KdtnUVrLJB5GSV1Y',
    appId: '1:337537219073:android:e16fe71efefc04ff8f1e00',
    messagingSenderId: '337537219073',
    projectId: 'furniapp-a28a9',
    storageBucket: 'furniapp-a28a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsdt6g7azALzryCxSlKYu8rKfaqvA1Ch0',
    appId: '1:337537219073:ios:6f46614b3cbae4de8f1e00',
    messagingSenderId: '337537219073',
    projectId: 'furniapp-a28a9',
    storageBucket: 'furniapp-a28a9.firebasestorage.app',
    iosBundleId: 'com.example.furniapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsdt6g7azALzryCxSlKYu8rKfaqvA1Ch0',
    appId: '1:337537219073:ios:6f46614b3cbae4de8f1e00',
    messagingSenderId: '337537219073',
    projectId: 'furniapp-a28a9',
    storageBucket: 'furniapp-a28a9.firebasestorage.app',
    iosBundleId: 'com.example.furniapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfkj-u3MJ93ZBUNc_85LXFnFIfniZqKg4',
    appId: '1:337537219073:web:c1114a7c1198fc008f1e00',
    messagingSenderId: '337537219073',
    projectId: 'furniapp-a28a9',
    authDomain: 'furniapp-a28a9.firebaseapp.com',
    storageBucket: 'furniapp-a28a9.firebasestorage.app',
  );

}